CREATE TABLE driver_record (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    submission_token CHAR(36) NOT NULL COMMENT '提交幂等令牌',
    driver_name VARCHAR(50) NOT NULL COMMENT '司机姓名',
    phone VARCHAR(20) NOT NULL COMMENT '手机号',
    license_plate VARCHAR(20) NOT NULL COMMENT '车牌号',
    vehicle_type VARCHAR(50) NOT NULL COMMENT '车型',
    destination VARCHAR(200) NOT NULL COMMENT '目的地',
    latitude DECIMAL(10, 7) NULL COMMENT '纬度',
    longitude DECIMAL(10, 7) NULL COMMENT '经度',
    location_address VARCHAR(500) NULL COMMENT '定位文字地址',
    location_accuracy DECIMAL(10, 2) NULL COMMENT '定位精度（米）',
    location_status VARCHAR(20) NOT NULL COMMENT '定位状态',
    located_at DATETIME(3) NULL COMMENT '设备获取定位时间（UTC）',
    created_at DATETIME(3) NOT NULL COMMENT '服务器提交时间（UTC）',
    updated_at DATETIME(3) NOT NULL COMMENT '最后修改时间（UTC）',
    updated_by VARCHAR(50) NULL COMMENT '最后修改管理员',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否软删除',
    deleted_at DATETIME(3) NULL COMMENT '删除时间（UTC）',
    deleted_by VARCHAR(50) NULL COMMENT '删除管理员',
    PRIMARY KEY (id),
    UNIQUE KEY uk_driver_record_submission_token (submission_token),
    KEY idx_driver_record_deleted_created (deleted, created_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='司机出车登记记录';
